// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rnyimfopoumlntlnzssh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJueWltZm9wb3VtbG50bG56c3NoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODM1OTc5MTcsImV4cCI6MjA5OTE3MzkxN30.naiSPUKpIJmLLpZ98sY7JCNvVJdqx6v7VjwoV4iqowg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});